= NNabla C Runtime for GDScript
:lang: ja
:doctype: book
:author: MizunagiKB
:toc: left
:toclevels: 3
:icons: font
:experimental:
:stem:


== このモジュールについて

このモジュールはSONYが開発している、link:https://github.com/sony/nnabla-c-runtime[NNabla C Runtime]をGDScriptから呼び出せるようにしたものです。

対応しているGodot Engineは4.1を想定しており、ビルドしたNNabla C Runtimeはv1.36.0となります。


== ビルド方法

NNabla C Runtime をビルドする場合は、バージョン指定を行ってください。

[source,zsh]
--
# v1.36.0を指定する場合の例
git checkout refs/tags/v1.36.0
--


=== Windows

[source]
--
pushd thirdparty\nnabla-c-runtime
build-tools\msvc\build.bat
popd
--

上のコマンドでビルド自体は完了しますが、Godot側とビルドオプションが異なっているためにリンクが失敗します。

現状では、ビルド完了後に VisualStudio でソリューションファイルを開いて /MT, /MTd でビルドされる様にコンパイルオプションを修正後、ビルドしなおしてください。

[source]
--
scons platform=windows target=template_debug
scons platform=windows target=template_release
--


=== macOS

[source,zsh]
--
pushd thirdparty/nnabla-c-runtime
# for Universal Binary
export CFLAGS="-arch x86_64 -arch arm64"
make nnabla-c-runtime-compile
popd

scons platform=macos target=template_debug
scons platform=macos target=template_release
--


== ライセンスについて

このプログラムはGodot EngineにあわせてMIT Licenseとして提供していますが、依存するNNabla C RuntimeはApache License 2.0となります。

ライセンス表記を行う際はご注意ください。
