= NNabla C Runtime for GDScript
:lang: ja
:doctype: book
:author: MizunagiKB
:toc: left
:toclevels: 3
:icons: font
:experimental:
:stem:


== このモジュールについて

このモジュールはSONYが開発している、link:https://github.com/sony/nnabla-c-runtime[NNabla C Runtime]をGDScript（Godot Engine 4.1）から呼び出せるようにしたものです。

学習済みモデルはNNB形式のみ対応しています。

=== 使い方の例

[source,gdscript]
--
# NNBファイルの読み込み
var rf = FileAccess.open("res://model.nnb", FileAccess.READ)
var rf_size = rf.get_length()
var nnb = rf.get_buffer(rf_size)
rf.close()

# NNabla C Runtimeの作成
nn_crt = GDNNablaCRuntime.new()
# NNabla C Runtimeの初期化
nn_crt.rt_allocate_context()
# NNBファイルを設定
nn_crt.rt_initialize_context(nnb)

# 1) 入力値を設定
var ary_i = PackedFloat32Array([1.0])
nn_crt.rt_input_buffer(0, ary_i)

# 2) 推論
nn_crt.rt_forward()

# 3) 出力値を取得
var ary_o = nn_crt.rt_output_buffer(0)

# 終了処理
nn_crt.rt_free_context()
--

NOTE: 何度も推論を行う場合は、1, 2, 3を連続して繰り返す事が出来ます。


== より詳しい使い方

モデルの生成を含めた使い方は以下のページを参照してください。

link:doc/USAGE.ja.adoc[]

== ビルド方法

NNabla C Runtime をビルドする前に、忘れずにバージョン指定を行ってください。

[source,zsh]
--
# v1.36.0を指定する場合の例
git checkout refs/tags/v1.36.0
--


=== Windows

[source]
--
pushd thirdparty\nnabla-c-runtime
build-tools\msvc\build.bat
popd
--

上のコマンドを実行するとビルド自体は完了するのですが、Godot側とビルドオプションが異なっているためにリンクが失敗します。

リンクが失敗する原因は、NNabla C RuntimeがMultiThreadDllでビルドされるのに対して、Godot EngineがMultiThreadでビルドされるためです。

現状でNNabla C Runtimeに手を加える事は考えていませんので、ビルド完了後に VisualStudio でソリューションファイルを開いて /MT, /MTd でビルドされる様にコンパイルオプションを修正してビルドしなおしてください。


[source]
--
scons platform=windows target=template_debug
scons platform=windows target=template_release
--

ビルドが完了すると以下のファイルがdemo/addons/gd_nnabla_c_runtime/bin以下に生成されます。

* libgd_nnabla_c_runtime.windows.debug.x86_64.dll
* libgd_nnabla_c_runtime.windows.release.x86_64.dll


=== macOS

macOSではUniversal Binaryに対応したビルドを行ってください。

[source,zsh]
--
pushd thirdparty/nnabla-c-runtime
# for Universal Binary
export CFLAGS="-arch x86_64 -arch arm64"
make nnabla-c-runtime-compile
popd

scons platform=macos target=template_debug
scons platform=macos target=template_release
--

ビルドが完了すると以下のファイルがdemo/addons/gd_nnabla_c_runtime/bin以下に生成されます。

* libgd_nnabla_c_runtime.macos.debug.framework
* libgd_nnabla_c_runtime.macos.release.framework


== ライセンスについて

このプログラムはGodot EngineにあわせてMIT Licenseとして提供しています。

ただし、このプログラムが依存しているNNabla C RuntimeはApache License 2.0ライセンスとなります。

ライセンス表記を行う際はご注意ください。

== 関連情報

* link:https://nnabla.org/[SONY Neural Network Libraries]
* link:https://github.com/sony/nnabla[sony / nnabla (GitHub)]
* link:https://github.com/sony/nnabla-c-runtime[sony / nnabla-c-runtime (GItHub)]
* link:https://github.com/MizunagiKB/gd_nnabla_c_runtime[MizunagiKB / gd_nnabla_c_runtime (GitHub)]

